class Interface:
    WIDTH = 90
    BOX_SEPARATOR_DISTANCE = 1
    INFO_BOX_HEIGHT = 5
    DUNGEON_MAX_WIDTH = 16
    DUNGEON_MAX_HEIGHT = 16
    DUNGEON_BOX_PADDING_HEIGHT = 2
    DUNGEON_BOX_PADDING_WIDTH = 2
    DUNGEON_BOX_WIDTH = DUNGEON_MAX_WIDTH + DUNGEON_BOX_PADDING_WIDTH
    DUNGEON_BOX_HEIGHT = DUNGEON_MAX_HEIGHT + DUNGEON_BOX_PADDING_HEIGHT
    DIALOG_BOX_WIDTH = (WIDTH // 2) - (DUNGEON_BOX_WIDTH // 2) - BOX_SEPARATOR_DISTANCE
    #DOUBLE PADDING TO MATCH DUNGEON BOX TOTAL HEIGHT
    DIALOG_BOX_HEIGHT = DUNGEON_BOX_HEIGHT + DUNGEON_BOX_PADDING_HEIGHT
    EQUIPMENT_BOX_HEIGHT = DUNGEON_BOX_HEIGHT + DUNGEON_BOX_PADDING_HEIGHT
    EQUIPMENT_BOX_WIDTH = WIDTH - (WIDTH // 3) - BOX_SEPARATOR_DISTANCE
    DESCRIPTION_BOX_WIDTH = WIDTH - (WIDTH // 3 * 2)
    LOG_BOX_HEIGHT = 7
    LOG_BOX_WIDTH = WIDTH
    HEIGHT = INFO_BOX_HEIGHT + DUNGEON_BOX_HEIGHT + LOG_BOX_HEIGHT

class Symbols:
    PLAYER = "@"

class Inventory:
    columns = [
        ("Name", 25),
        ("Type", 15),
        ("Weight", 9),
        ("Volume", 9),
    ]

    available_lines = 17