class Interface:
    WIDTH = 90
    INFO_BOX_HEIGHT = 5
    DUNGEON_MAX_SIZE = 16
    DUNGEON_BOX_PADDING = 4
    DUNGEON_BOX_SIZE = DUNGEON_MAX_SIZE + DUNGEON_BOX_PADDING
    DIALOG_BOX_WIDTH = (WIDTH // 2) - (DUNGEON_BOX_SIZE // 2) - 1
    DIALOG_BOX_DIMENSIONS = (DUNGEON_BOX_SIZE, DIALOG_BOX_WIDTH)
    LOG_BOX_HEIGHT = 7
    LOG_BOX_WIDTH = WIDTH
    HEIGHT = INFO_BOX_HEIGHT + DUNGEON_BOX_SIZE + LOG_BOX_HEIGHT